services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  In2code\Texter\:
    resource: '../Classes/*'

  In2code\Texter\Controller\AjaxController:
    public: true

  In2code\Texter\Domain\Repository\LlmRepository:
    public: true